export { ReactComponent as ErrorIcon } from './error.svg'
export { ReactComponent as Timer } from './timer.svg'
export { ReactComponent as Pause } from './pause.svg'
export { ReactComponent as Play } from './play.svg'
export { ReactComponent as Star } from './star.svg'
