export enum appTypes {
  USER_REGISTRATION_START = 'APP/USER_REGISTRATION_START',
  FETCH_SUCCESS = 'APP/FETCH_SUCCESS',
  FETCH_ERROR_SHOW = 'APP/FETCH_ERROR_SHOW',
  FETCH_ERROR_HIDE = 'APP/FETCH_ERROR_HIDE',
}
